name: Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: $GITHUB_ACTOR
        password: "${{ secrets.GITHUB_TOKEN }}"
    - name: Generate a container image
      run: |
        version=$(cat VERSION)
        docker build . -t ghcr.io/${USERNAME_OR_ORG}/github-updates:${version}
        docker push ghcr.io/${USERNAME_OR_ORG}/github-updates:${version}
      shell: bash
      env:
        USERNAME_OR_ORG: "${{ github.repository_owner }}"
    - name: Increment the pom version
      run: |
        current_version=$(cat VERSION)
        if [[ "$current_version" =~ v([0-9]+)\.([0-9]+) ]]; then
          major="${BASH_REMATCH[1]}"
          minor="${BASH_REMATCH[2]}"
        else
          echo "Invalid version format. Expected format: v<major>.<minor>"
          exit 1
        fi
        minor=$((minor + 1))
        new_version="v${major}.${minor}"
        echo "$new_version" > VERSION
      shell: bash
    - name: Create Pull Request with new PRs
      uses: peter-evans/create-pull-request@v3
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        branch-suffix: timestamp
        title: Increment version after release
        labels: auto-version-increment
        signoff: true
        delete-branch: false
        commit-message: Auto increment version after release
